// packages/playground/angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'htmlplus-playground-angular';
}

<div class="center">
    <plus-dialog-toggler connector="dialog-animation">
        Open
    </plus-dialog-toggler>
</div>
<plus-dialog animation="fade" connector="dialog-animation">
    <plus-dialog-content>
        <plus-dialog-header>
            Dialog Title
        </plus-dialog-header>
        <plus-dialog-body>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et
            dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex
            ea commodo consequat.
        </plus-dialog-body>
        <plus-dialog-footer>
            <plus-dialog-toggler>
                Close
            </plus-dialog-toggler>
        </plus-dialog-footer>
    </plus-dialog-content>
</plus-dialog>

// packages/playground/vue/src/App.vue
<template>
  <h1>
    Vue
      <div class="center">
    <plus-dialog-toggler connector="dialog-animation">
      Open
    </plus-dialog-toggler>
  </div>
  <plus-dialog animation="fade" connector="dialog-animation">
    <plus-dialog-content>
      <plus-dialog-header>
        Dialog Title
      </plus-dialog-header>
      <plus-dialog-body>
        Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
      </plus-dialog-body>
      <plus-dialog-footer>
        <plus-dialog-toggler>
          Close
        </plus-dialog-toggler>
      </plus-dialog-footer>
    </plus-dialog-content>
  </plus-dialog>
  </h1>
</template>
